#!/usr/bin/env ruby

require "diplomat"
require "redis"
require "socket"

# Redis/Sentinel
REDIS_MASTERS = ENV.fetch("REDIS_MASTERS").split(" ")
MASTER_CONSUL_SERVICE_PREFIX = ENV.fetch("MASTER_CONSUL_SERVICE_PREFIX")
SENTINEL_SERVICE = ENV.fetch("SENTINEL_SERVICE")
QUORUM = ENV.fetch("QUORUM")

# Host where Consul API is running
CONSUL_HOST = ENV.fetch("CONSUL_HOST")

# Port to expose http check
CHECK_PORT = ENV.fetch("CHECK_PORT")

# Interval that which each pod is evaluated
INTERVAL = ENV.fetch("INTERVAL", "10").to_i

Diplomat.configure do |config|
  config.url = "http://#{CONSUL_HOST}:8500"
end

class Pod

  attr_reader :name, :service_name, :servers, :sentinels

  def initialize(name)
    @name = name
    @service_name = "#{MASTER_CONSUL_SERVICE_PREFIX}#{name}"
    @servers = []
    @error_lock = Mutex.new
  end

  def refresh_servers!
    @servers = Diplomat::Service.get(service_name, :all).map do |node|
      Redis.new host: node.Address, port:  node.ServicePort
    end
  end

  def single_master?
    servers.find_all do |server|
      server.info["role"] == "master"
    end.size == 1
  end

  def master
    servers.find do |server|
      server.info["role"] == "master"
    end
  end

  def refresh_sentinels!
    @sentinels = Diplomat::Service.get(SENTINEL_SERVICE, :all).map do |node|
      Redis.new host: node.Address, port: node.ServicePort
    end
  end

  def configure_sentinels!
    sentinels.each do |sentinel|
      next unless sentinel.sentinel("masters").any? do |sentinel_master|
        sentinel_master["name"] == name
      end
      sentinel.sentinel "monitor", name, master.client.host, master.client.port, QUORUM
    end
  end

  def error
    @error_lock.synchronize { @error }
  end

  def error=(e)
    @error_lock.synchronize { @error = e }
  end
end

Thread.abort_on_exception = true

threads = []
pods = []

REDIS_MASTERS.each do |master|

  pods << Pod.new(master)
  pod = pods.last

  threads << Thread.new do

    loop do

      pod.refresh_servers!

      if pod.servers.empty?
        pod.error = "No servers in #{pod.name}."
        sleep INTERVAL
        next
      end

      if !pod.single_master?
        pod.error = "Many masters detected in #{pod.name}."
        sleep INTERVAL
        next
      end

      pod.error = nil

      pod.refresh_sentinels!
      pod.configure_sentinels!

      sleep INTERVAL
    end
  end
end

http_health_check = TCPServer.new("0.0.0.0", CHECK_PORT)

threads << Thread.new do
  loop do
    socket = http_health_check.accept
    errors = pods.map(&:error).compact
    status, body = if errors.empty?
      ["200 OK", ""]
    else
      ["500 Internal Server Error", errors.join(", ")]
    end
    socket.print <<-EOR
HTTP/1.1 #{status}
Content-Type: text/plain
Content-Length: #{body.bytesize}
Connection: close

#{body}
EOR
    socket.close
  end
end

threads.each(&:join)
